# Generated by Django 6.0.3 on 2026-06-21 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_applicantdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicantdocument',
            unique_together={('applicant', 'document_type')},
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='document_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_column='verified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist'), ('registered', 'Registered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='document_type',
            field=models.CharField(choices=[('cnic_front', 'CNIC Front'), ('cnic_back', 'CNIC Back'), ('domicile', 'Domicile'), ('photograph', 'Photograph'), ('matric_marksheet', 'Matric Marksheet'), ('matric_certificate', 'Matric Certificate'), ('inter_marksheet', 'Inter Marksheet'), ('inter_certificate', 'Inter Certificate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='file_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='AdmissionDecision',
            fields=[
                ('decision_id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist')], max_length=20)),
                ('decision_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('offered_section', models.CharField(blank=True, max_length=20, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('merit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('merit_position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='decision', to='admissions.admissionapplication')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admission_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admissions_decision',
            },
        ),
        migrations.CreateModel(
            name='AdmissionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('documents_verified', 'Documents Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('registered', 'Registered')], max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='admissions.admissionapplication')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admission_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admissions_log',
            },
        ),
        migrations.RemoveField(
            model_name='applicantdocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='applicantdocument',
            name='id',
        ),
        migrations.RemoveField(
            model_name='applicantdocument',
            name='title',
        ),
    ]
