# Generated by Django 6.0.3 on 2026-06-21 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('admissions', '0003_alter_applicantdocument_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='academics.degreeprogram'),
            preserve_default=False,
        ),
    ]
